### ISSUE TITLE
JS/TS colors are just blue

### ISSUE THREAD

**Issue by svipas** [s1e2b3i4/onenord-vscode#6]
1. I'm not sure if it's okay to use `meta.function-call` since it takes `this`, maybe it should have a separate color?
2. Also, why properties are the same color as functions? Is it intentional?
3. Take a look at 26 line you will see that `this` is white, because it doesn't have theme selector.

Maybe @rmehri01 could help and say what actual colors it should be? I could try to fix it by creating a PR.

BTW: Theme is amazing, I loved Nord and at the same time One Dark Pro, but now it is combined into one ❤️ 

<img width="840" alt="image" src="https://github.com/s1e2b3i4/onenord-vscode/assets/10441177/4d614201-b714-43f4-b30e-b672a5664076">

**Comment by s1e2b3i4** [comment]
Hey @svipas Great to hear that you like the theme!
Your screenshot indeed looks very strange and definitely not like it is supposed to look.
My original Idea was to be as close as possible to the original theme, so I compare all changes in this port with the look in PyCharm, in my case. 

When I test it with a code snippet from one of your repos, it looks fine to me. If this problem with the blue color remains, please let me know and I can test it with the causing code.
Overall, the theme is not yet optimized for all major languages. So if there is something you want to change for JS/TS, please don't hesitate to let me know or open a PR.

![image](https://github.com/s1e2b3i4/onenord-vscode/assets/28140755/3b83e625-272b-4e6f-9c7f-9199aa995665)

**Comment by svipas** [comment]
What you show here is functions, my code is in classes so maybe that's the issue.

You can use this example: https://github.com/microsoft/vscode/blob/8a2bfc6384fcfd53ae2451af1340094edb72b8e1/src/vs/workbench/browser/parts/editor/editorTitleControl.ts

Open it by copy-pasting into editor and go to line 116 and below you will see blue colors

<img width="470" alt="image" src="https://github.com/s1e2b3i4/onenord-vscode/assets/10441177/e8c285d1-4bc2-47cf-b12e-71757c8f36df">

If we let's say take an example of this part: `this.breadcrumbsControl?.update();` it should have different color for `this` and `breadcrumbsControl`, `update()` should be blue since it's a function.

**Comment by svipas** [comment]
We definitely need @rmehri01 help here 🙏

**Comment by rmehri01** [comment]
Hey, my Helix theme looks something like this for reference:

![Screenshot from 2023-10-31 07-57-58](https://github.com/s1e2b3i4/onenord-vscode/assets/52933714/2344d283-5f0e-4322-8039-b7582d514021)

I can't get the IntelliJ theme to quite highlight it correctly because of missing other files:

![image](https://github.com/s1e2b3i4/onenord-vscode/assets/52933714/12899f5a-3d3d-420a-b0ee-826e625f472c)

The main difference might just be that `this` is also blue which is throwing off the balance? You could also choose a different color for the fields which may help like in the IntelliJ one but I personally prefer the former screenshot :)

**Comment by svipas** [comment]
I kinda starting to like the blue color, so created a [PR](https://github.com/s1e2b3i4/onenord-vscode/pull/16) to fix `this` and `super` and I think we are good to go since it matches the original theme.

**Comment by s1e2b3i4** [comment]
Hey @svipas 
The PR looks good. Thanks for your contribution!
Because I merged #5, your changes now have to go in the new yml file. I would like to help you with this, but it seems that you have not allowed maintainers to push commits to your PRs. If you change that, I can easily translate your changes to the new format.

**Comment by svipas** [comment]
@s1e2b3i4 Done for all opened PRs.

**Comment by Uaitt** [comment]
@svipas I still see that all your PRs modify the old JSON file and not the current YML one 🤔

**Comment by svipas** [comment]
@Uaitt @s1e2b3i4 asked for:

> it seems that you have not allowed maintainers to push commits to your PRs

**Comment by s1e2b3i4** [comment]
The issue is now resolved via https://github.com/s1e2b3i4/onenord-vscode/tree/bb69a332e4d21084c291a07de19e4889a5ac95ad.

Thank you for your patience, and thanks for your contribution and participation in the discussion!
